### ISSUE TITLE
CC-01-015 User credentials and other sensitive data in log file  (High)

### ISSUE THREAD

**Issue by cure53** [igarape/copcast-server#104]
The server application running the api logs sensitive data into log files. This includes passwords users send to the server via the login form. Logging plaintext passwords makes it pointless to store password hashes in the user database. An attacker who gains access to the server could easily read the passwords of the users from past logins

**Logfile:**
/home/copcast/.forever/__oO.log

**Example Request:**
```
POST /token 200 42.445 ms - 270
kB3Xp3t4n26INw3ovsBEDI1VstiRZEtzdYniPOZ9tko=
p12osApdgfaoMZK7i9rN6z9DiI3nvA3s2R00zSX+pjYBvHi+uwCM1d11gnSFMgIXubYt8qFSIP0Wa/2fNl+F93/YkXSSRJbwFD5kiF1SNv1vCFvZD2TqE7/ttPpbCHg4KV2ic+H2XShJDJKiEuGkZ7KIJ8rftuwkI3qS0qB0vLO3aBgfjS70dwinrIxmoNdyhvPlFaQ7xMIRpyGXjMFGxKeeWSOTu47YLHFMh8XwIvnvo+hgIT86xiz5DfI8zjwnCwNgILdFKo4bp+VIMiMXnOydpc1DpvVO0VsYWL0BDd2R0ujy6tfmlf2zgaRV7vDmam0lh8v/CvPX6O5OxMiFsA==
Mysecretpassword
```

**Affected Code:**
_/copcast-server-webrecorder/lib/db/user.js_

```
console.log(salt_part);
console.log(hash);
console.log(password);
```

Logging sensitive data is not recommended. In case the logged messages are needed for debugging purposes the output should only be printed in case a debug flag is set.

**Comment by cure53** [comment]
Is there a commit for this fix? Or was this covered by the other commits?

**Comment by brunosiqueira** [comment]
@kldavis4 do you have mapped the commit for this issue?
