### ISSUE TITLE
CC-01-017 Sequelize Injection on several DB queries (Info)

### ISSUE THREAD

**Issue by cure53** [igarape/copcast-server#109]
As an ORM the NodeJS module Sequelize is used. In combination with the JSON middleware this can allow users to perform Sequelize injections. For example lib/signing/index.js:

`db.registration.findOne({where: {imei: req.body.imei, simid: req.body.simid}})`

The request body value of IMEI and SIMID are passed directly into a where-clause of Sequelize. Because of the JSON middleware, IMEI and SIMID could be a JSON object like:

`{"imei": {"$iLike": "%"}, "simid": {"$iLike": "%"}}`

Another example is the passsword forgot/confirm token functionality:

**Affected File:**
Copcast-server-webrecorder\lib\users\index.js
```
app.post('/users/changePasswordToken/:token', function (req, res) {
    db.user.find({where: {rememberToken: req.params.token}}).then(function (user) {
      if (user) {
        user.hashPassword(req.body.password, function () {
          user.rememberToken = '';
          user.save().then(function () {
```

Again, user controlled data is passed in the where clause of Sequelize. By using the _$iLike_ operator it would be possible to set a new password for any user, who has currently used the password forgotten functionality. User supplied values should always be verified.

**Comment by brunosiqueira** [comment]
same of #107

**Comment by cure53** [comment]
Issue was fixed successfully, fix confirmed!
