### ISSUE TITLE
Steganographic watermarking to add an invisible second layer of auditability

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-server#31]
Create a watermark in all the videos with copcast logo, name of the user who exported the file and time of export.

**Comment by eclectiqus** [comment]
Great idea to make use of those LSBs!

**Comment by martelli** [comment]
@brunosiqueira  As mentioned by Lally, this steganographic information could be easily removed by re-encoding the video. Could we close this issue?
