### ISSUE TITLE
Video Speedup on the History Screen

### ISSUE THREAD

**Issue by ebadran** [igarape/copcast-server#49]
When reviewing flagged or incident footage (e.g. for a criminal investigation, or a disciplinary measure against an officer) a video speedup feature may be enabled to allow users to skim through footage at 2x, 4x, 8x speed.

**Comment by arthurvasconcelos** [comment]
Issue moved to [igarape/copcast-admin #288](https://github.com/igarape/copcast-admin/issues/288) via [**ZenHub.io**](https://www.zenhub.io/)
